version: '3.8'

volumes:
  mariadb:

services:
  mariadb:
    image: mariadb:10.7
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: hotsapi
      MARIADB_USER: hotsapi
      MARIADB_PASSWORD: secret
    volumes:
      - mariadb:/var/lib/mysql

  php-cli:
    build:
      context: ./docker/dev
      dockerfile: php-cli/Dockerfile
    environment:
      - APP_URL=http://localhost:8080
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=hotsapi
      - DB_USERNAME=hotsapi
      - DB_PASSWORD=secret
    volumes:
      - ./:/app

  php-fpm:
    build:
      context: ./docker/dev
      dockerfile: php-fpm/Dockerfile
    environment:
      - APP_URL=http://localhost:8080
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=hotsapi
      - DB_USERNAME=hotsapi
      - DB_PASSWORD=secret
    volumes:
      - .:/app

  nginx:
    build:
      context: ./docker/dev/nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/app
