version: '3.8'

volumes:
  mariadb:

services:
  mariadb:
    image: mariadb:10.7
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: hotsapi
      MARIADB_USER: hotsapi
      MARIADB_PASSWORD: secret
    volumes:
      - mariadb:/var/lib/mysql

  artisan:
    build:
      context: .
      dockerfile: docker/Dockerfile.development
    entrypoint: ["php", "artisan"]
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YmFzZTY0X2tleV9fYmFzZTY0
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=hotsapi
      - DB_USERNAME=hotsapi
      - DB_PASSWORD=secret
    volumes:
      - .:/var/www/hotsapi

  hotsapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.development
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/hotsapi

